// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_BE.Models;

public partial class DeviceParameterLogs
{
    public long Id { get; set; }

    public int DeviceParameterId { get; set; }

    public string LogValue { get; set; }

    public DateTime? Timestamp { get; set; }
}