// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_BE.Models;

public partial class Device
{
    public int Id { get; set; }

    public int AreaId { get; set; }

    public string DeviceName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }
}